
name = "docker-training-nl"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "docker-training.nl/*"
zone_id = "204c7f634337f80bc1c89d743db9c6cb"

[site]
bucket = "../../packages/docker-training.nl/out/"
entry-point = "../_static-site"

