generate-config:
  stage: build
  script: echo '{"job1":{"script":"echo hello"},"job2":{"script":"echo hello2"}}' > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
