
name = "docker-utbildning-se"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "docker-utbildning.se/*"
zone_id = "829bd83e828315316d122a9c8cc811fc"

[site]
bucket = "../../packages/docker-utbildning.se/out/"
entry-point = "../_static-site"

