
name = "training-kubernetes.is"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "training.kubernetes.is/*"
zone_id = null

[site]
bucket = "../../packages/training.kubernetes.is/out/"
entry-point = "../_static-site"

