
name = "dockerschulung-de"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "dockerschulung.de/*"
zone_id = "4567f24513ada6e3b6073970c1793365"

[site]
bucket = "../../packages/dockerschulung.de/out/"
entry-point = "../_static-site"

