
name = "skoleni-docker-cz"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "skoleni-docker.cz/*"
zone_id = "194802c4831f1070d5304c220342e28c"

[site]
bucket = "../../packages/skoleni-docker.cz/out/"
entry-point = "../_static-site"

