
name = "ccc-oxs.cz"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "ccc.oxs.cz/*"
zone_id = null

[site]
bucket = "../../packages/ccc.oxs.cz/out/"
entry-point = "../_static-site"

