
name = "skoleni-proxmox-cz"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "skoleni-proxmox.cz/*"
zone_id = "2ae93985103f3fffe02c7af97f746593"

[site]
bucket = "../../packages/skoleni-proxmox.cz/out/"
entry-point = "../_static-site"

