
name = "salzburgdevops-com"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "salzburgdevops.com/*"
zone_id = "144ed2fc0df524316fd9024be8e937e3"

[site]
bucket = "../../packages/salzburgdevops.com/out/"
entry-point = "../_static-site"

