
name = "skoleni-rancher-cz"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "skoleni-rancher.cz/*"
zone_id = "892b95d6499d24ffbb725f8670114371"

[site]
bucket = "../../packages/skoleni-rancher.cz/out/"
entry-point = "../_static-site"

