
name = "skoleni-kubernetes-cz"
type = "webpack"
account_id = "8a5e13ad9edd5be4595027085cf61ce7"
workers_dev = false
route = "skoleni-kubernetes.cz/*"
zone_id = "627aeacb9162da03a0cee367d4e6c6e3"

[site]
bucket = "../../packages/skoleni-kubernetes.cz/out/"
entry-point = "../_static-site"

